/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_cheng_ffmpegdemo_MyVideoPlayer */

#ifndef _Included_com_example_cheng_ffmpegdemo_MyVideoPlayer
#define _Included_com_example_cheng_ffmpegdemo_MyVideoPlayer
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_cheng_ffmpegdemo_MyVideoPlayer
 * Method:    init
 * Signature: ()V
 */
JNIEXPORT void JNICALL
Java_com_example_cheng_ffmpegdemo_MyVideoPlayer_render(JNIEnv *, jobject ,jstring , jobject);

JNIEXPORT void JNICALL
Java_com_example_cheng_ffmpegdemo_MyVideoPlayer_sound(JNIEnv *, jobject ,jstring , jstring);


#ifdef __cplusplus
}
#endif
#endif
